services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: cca-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - cca-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: cca-otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    depends_on:
      - jaeger
    ports:
      - "4317"
      - "4318"
      - "55679"
    networks:
      - cca-network

  prometheus:
    image: prom/prometheus:latest
    container_name: cca-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - checkout
      - inventory
      - payment
    networks:
      - cca-network

  payment:
    build:
      context: .
      dockerfile: services/payment/Dockerfile
    container_name: cca-payment
    environment:
      OTEL_SERVICE_NAME: payment
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    ports:
      - "8003:8003"
    depends_on:
      - otel-collector
    networks:
      - cca-network

  inventory:
    build:
      context: .
      dockerfile: services/inventory/Dockerfile
    container_name: cca-inventory
    environment:
      PAYMENT_SERVICE_URL: http://payment:8003
      OTEL_SERVICE_NAME: inventory
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    ports:
      - "8002:8002"
    depends_on:
      - payment
      - otel-collector
    networks:
      - cca-network

  checkout:
    build:
      context: .
      dockerfile: services/checkout/Dockerfile
    container_name: cca-checkout
    environment:
      INVENTORY_SERVICE_URL: http://inventory:8002
      OTEL_SERVICE_NAME: checkout
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    ports:
      - "8001:8001"
    depends_on:
      - inventory
      - otel-collector
    networks:
      - cca-network

networks:
  cca-network:
    driver: bridge
